-- =============================================================================
-- PizzaManager — SQL UPGRADE (solo modifiche da qui in avanti)
-- =============================================================================
--
-- Lo storico degli script manuali è stato suddiviso in moduli riutilizzabili:
--   sql/modules/01_fidelity_tenant.sql … 10_punti_vendita_lat_lng_view.sql
-- Esegui i moduli IN ORDINE su un database nuovo o se mancano oggetti elencati
-- nel README della cartella modules.
--
-- Questo file serve per:
--   • Nuove migration incrementali (copia-incolla in Supabase SQL Editor dopo review)
--   • Oppure: aggiungi un file in supabase/migrations/YYYYMMDDHHMMSS_nome.sql per CLI
--
-- (Nessuna istruzione DDL obbligatoria qui finché non serve una modifica nuova.)
--
-- =============================================================================

-- Esempio (commentato) — decommentare quando serve:
-- ALTER TABLE core.ordini ADD COLUMN IF NOT EXISTS esempio_colonna TEXT;
